name: Publish to Pypi

on:
  release:
    types: [published]

jobs:
  create-release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/py-') && !github.event.release.draft && !github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Download files from the release
        run: python .github/workflows/download-libhumancode-release-assets.py "${{ github.event.release.tag_name }}" dist/
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
